version: '3'

networks:
  my-network:
    driver: bridge

volumes:
  node_modules:

services:
  ### nginx #################
  nginx:
    build:
      context: ./nginx
    # image: custom-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    # restart: always
    depends_on:
      - nodejs
    networks:
      - my-network

  ### node ##############
  nodejs:
    build:
      context: ./node
    ports:
      - 127.0.0.1:7001:7001
    volumes:
      - ./node/nodeService:/app/nodeService
      - node_modules:/app/nodeService/node_modules
    # restart: always
    networks:
      - my-network
